### ISSUE TITLE
imgAddNoise requires an infinite adressing space

### ISSUE THREAD

**Issue by ProgVal** [dcoeurjo/lectureDG#21]
When running imgAddNoise from a process bounded to an adressing space of 2GB (using rlimit), I get this error:

```
libgomp: Thread creation failed: Resource temporarily unavailable
```

On this line:

```
  KanungoNoise<Binarizer, Z2i::Domain> kanungo(predicate, image.domain(), noise);
```

I tried increasing the bound to a larger value (>= 100GB), but I still get this error.

**Comment by dcoeurjo** [comment]
I think this this issue has been fixed in the master of DGtal.  Let's close this issue and see if the problem still occurs for the 2016 promo;)
